title: Priyam's blog
author: Priyam Tejaswin
email: priyamtejaswin@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Temet Nosce.

# social links
github_username:  priyamtejaswin

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md # This has been repurposed to be `about.md` because index.md is the landing page.
- project.md # Empty blog file with all the "project" posts.

# Build settings
theme: minima
highlighter: rouge
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
 - jekyll-feed
 - jekyll-seo-tag
